### ISSUE TITLE
title actions produce error in IE11

### ISSUE THREAD

**Issue by digital88** [surveyjs/survey-library#3143]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When opening page with survey in Internet Explorer 11, code in file src\knockout\components\action-bar\action-bar.ts (and probably same in src\knockout\components\progress\buttons.ts) in method ```ko.components.register(...)``` at line ```const container: HTMLDivElement = componentInfo.element.nextElementSibling;``` returns undefined container because IE do not expose nextElementSibling on comment nodes. ResponsivityManager then crashes at line ```this.resizeObserver.observe(this.container.parentElement);```

### What is the expected behavior?
Make code return container to pass to ResponsivityManager class

### How would you reproduce the current behavior (if this is a bug)?
Go open page in IE 11 https://surveyjs.io/Examples/Library (you also need to polyfill object.assign and ResizeObserver)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Library

Test code

```
your_code_here

```

### Specify your

* browser: IE 11
* browser version: 11.0.9600.17498 update version 11.0.15
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.8.56

**Comment by andrewtelnov** [comment]
@digital88 Fixed by the commit above.

Thank you,
Andrew

**Comment by digital88** [comment]
> @digital88 Fixed by the commit above.
> 
> Thank you,
> Andrew

Thanks for quick reply, but you also have object.assign in 'src\action-bar.ts'.

Also knokout 3.5.1, which you use as dependency, uses object.assign within its internals.

So as I said it need to be global polyfill.

And maybe I didn't word it correctly, but my bug report was about: ```const container: HTMLDivElement = componentInfo.element.nextElementSibling;``` returns undefined because IE does not expose nextElementSibling on comment nodes. So object.assign and ResizeObserver are just side bugs here )

**Comment by andrewtelnov** [comment]
@digital88 OK, We will review it more carefully.

Thank you,
Andrew

**Comment by digital88** [comment]
@tsv2013 Can you please explain why it's closed? If I manually polyfill ResizeObserver in IE this fix will still crash in IE11.

**Comment by tsv2013** [comment]
We've checked our code and samples. The above mentioned commit https://github.com/surveyjs/survey-library/commit/9502ffe010c9722fa6243218f16a4e478546c64a actually fixes the console error related to undefined `ResponsivityManager`.

This responsivity behavior (buttons collapse into popup menu) is related to action items only (buttons) that can be available in question title. And this responsivity is not supported in IE11. Actions in question title will be available in IE11 but they don't support responsive behavior. With the information that IE11 will be officially retired by MS in a year (https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/) I hope you understand us in our strategy not to support new features for deprecated browsers.

Console error is eliminated. That's why we treat this issue as closed.

**Comment by digital88** [comment]
Ok, I understand. Thanks for clarification.
