### ISSUE TITLE
Generate JSON Survey Schema - Bugs found

### ISSUE THREAD

**Issue by BinoDino** [surveyjs/survey-library#6227]
# Generate JSON Survey Schema - Bugs found

Hi, 
I am currently working with the surveyjs form library. I used the `Survey.Serializer.generateSchema()` method in order to create the JSON schema for the survey. That is when I encountered some bugs in the schema +  got error message "schema is invalid" using `Ajv` library. 

Would be great if you could take a look at it 🙂 Sorry for the long message and thank you!

### property `visible`

```json
{
  "properties": {
     "visible": {
         "type": "string"
      }
   }
}

```

### properties `title` and `description`

```json
{
  "properties": {
     "title": {
         "type": "string"
      },
     "description": {
         "type": "string"
      }
   }
}

```

### empty `enum` properties in schema

```json
{
  "properties": {
    "questionTitlePattern": {
          "type": "string",
          "enum": []
      }
   },
  "definitions": {
    "question": {
       "properties": {
         "page": {
             "type": "string",
             "enum": []
         }
       }
     },
    "panel": {
     "allOf": [
        {},
        {
         "properties": {
            "page": {
             "type": "string",
             "enum": []
            }
          }
        }
     ]
   }
  }
}

```

### properties `questions` (and others)

```json
{
  "properties": {
     "questions": {
         "type": "array",
         "items": [ { }, { }, { } ]
      }
   }
}

```

### references

`$id`:

```json

{
   "htmlconditionitem": {
        "$id": "#htmlconditionitem"
   }
}

```

in `properties`:

```json
{
  "properties": {
     "completedHtmlOnCondition": {
          "type": "array",
          "items": {
              "$ref": "#htmlconditionitem"
          }
      }
   }
}

```

in `definitions`:

```json
{
  "definitions": {
     "htmlconditionitem": {
          "type": "object",
          "$id": "#htmlconditionitem",
          "allOf": [
              {
                  "$ref": "#expressionitem"
              },
              {
                  "properties": {
                      "html": {
                          "type": "string"
                      }
                  }
              }
          ]
      }
}
```

### missing schemas

in `definitions/selectbase/allOf/{1}/properties/choicesByUrl`:

```json
"choicesByUrl": {
    "type": "array",
    "items": {
        "$ref": "#ChoicesRestful"
    }
}
```

in `definitions/text/allOf/{1}/properties/dataList`:

```json
"dataList": {
    "type": "array",
    "items": {
        "$ref": "#string"
    }
}
```

### property `visible`

`visible` is of type `boolean`.

```json
{
  "properties": {
     "visible": {
         "type": "boolean"
      }
   }
}

```

### properties `title` and `description`

`title` and `description` (and others?) are either a string or a translation object. 

```json
{
  "properties": {
     "title": {
         "oneOf": [
              { "type": "string"},
              { "$ref": "path/to/some/translation/object"}
          ]
      },
     "description": {
          "oneOf": [
              { "type": "string"},
              { "$ref": "path/to/some/translation/object"}
          ]
      }
   }
}

```
### empty `enum` properties in schema

empty `enum` properties are not allowed

### properties `questions` (and others)

Syntax error. Must be `anyOf`: 

```json
{
  "properties": {
     "questions": {
         "type": "array",
         "items": {
            "anyOf": [ { }, { }, { } ]
      }
   }
}

```

Also affected: 
* `triggers`
* `defintions/panelbase/properties/elements`
* `defintions/question/properties/validators`
* `defintions/matrixdropdowncolumn/properties/validators`
* `defintions/multipletextitem/properties/validators`
* `definitions/nonvalue/allOf/{1}/properties/validators`
* `definitions/paneldynamic/allOf/{1}/properties/templateElements`

### references

`$id` - no hash symbol `#`

```json

{
   "htmlconditionitem": {
        "$id": "htmlconditionitem"
   }
}

```

in `properties` - path is `#/definitions/id`:

```json
{
  "properties": {
     "completedHtmlOnCondition": {
          "type": "array",
          "items": {
              "$ref": "#/definitions/htmlconditionitem"
          }
      }
   }
}

```

in `definitions` - hash symbol `#` after id name:

```json
{
  "definitions": {
     "htmlconditionitem": {
          "type": "object",
          "$id": "#htmlconditionitem",
          "allOf": [
              {
                  "$ref": "expressionitem#"
              },
              {
                  "properties": {
                      "html": {
                          "type": "string"
                      }
                  }
              }
          ]
      }
}
```

### missing schemas

provide missing schemas `choicesRestful` and `string`

### Specifications

* surveyjs platform (angular or react or jquery or knockout or vue): Angular
* surveyjs version:  
  * survey-angular-ui: 1.9.86
  * survey-core: 1.9.86

**Comment by andrewtelnov** [comment]
@BinoDino I believe I have fixed everything, except localization string class.
I could not figure out how to define it.
It is an object that can have limited number of pairs:  `{ {locName1: locValue1}, {locName2: locValue2} }`.
Where locName is an enum ["default", "en", "fr", ...] and locValue is a string.

Thank you,
Andrew

**Comment by BinoDino** [comment]
Thank you very much for your fast feedback. I really appreciate that. 

I think the only way to define the localization string class would be like this: 

```json
{
  "definitions": {
     "localization": {
        "type": "object",
         "$id": "#localization",
         "properties": {
             "default": {
               "type": "string"
              },
              "ca": {
               "type": "string"
              },
              "cy": {
                "type": "string"
              },
              "da": {
                "type": "string"
              },
              "de": {
                 "type": "string"
              },
             (and so on)
         }
      }
   }
}
```

and then reference it like this (properties and definitions): 

```json
{
  "properties": {
     "title": {
          "oneOf": [
              { "type": "string"},
              { "$ref": "#/definitions/localization"}
          ]
      }
   },
 "definitions": {
    "itemvalue": {
        "type": "object",
        "properties": {
          "text": {
            "oneOf": [
              { "type": "string" },
              { "$ref": "localization#" }
            ]
          }
      }
    }
  }
}
```

**Comment by BinoDino** [comment]
@andrewtelnov sorry to write again, but I have found more bugs on the JSON schema.

### The issues are the following: 

**1. Wrong data types**

* `showCommentArea`, `isRequired`, `readOnly` should be of type  `boolean`

```json
{
  "description":{
     "question": {
         "properties": {
           "showCommentArea": {
              "type": "string"
           },
           "isRequired": {
              "type": "string"
           },
           "readOnly": {
               "type": "string"
          }
       }
     }
  }
}
```

**2. Double listing of properties** 

Example 1 (`showCommentArea` already listed in `question`): 

```json
{
   "definitions": {
       "selectbase": {
          "allOf": [
              {"$ref": "question#"},
              { "properties": {
                  "showCommentArea": {
                    "type": "string"
                   }
                }
             }
          ]
      }
   }
}
```

Example 2 (`isRequired`, `readOnly` already listed in `question`): 

```json
{
   "definitions": {
       "expression": {
          "allOf": [
              {"$ref": "question#"},
              { "properties": {
                  "isRequired": {
                    "type": "string"
                   },
                   "readOnly": {
                    "type": "string"
                   }
                }
             }
          ]
      }
   }
}
```
See also in 
* `defintions/nonvalue/allOf/{1}/properties/isRequired`
* `defintions/nonvalue/allOf/{1}/properties/readOnly`
* `defintions/panel/allOf/{1}/properties/isRequired`
* `defintions/panel/allOf/{1}/properties/readOnly`

**3. Double listing and wrong data type on second listing**

Initially `separateSpecialChoices` is `boolean`
```json
{
   "definitions": {
       "selectbase": {
          "allOf": [
              {"$ref": "question#"},
              { "properties": {
                  "separateSpecialChoices": {
                      "type": "boolean"
                    }
                }
             }
          ]
      },
    "checkboxbase": {
          "type": "object",
          "$id": "checkboxbase",
          "allOf": [
            {
              "$ref": "selectbase#"
            }
         ]
     }
   }
}
```

Here it is a `string` now:

```json
{
   "definitions": {
      "radiogroup": {
          "allOf": [
            {
              "$ref": "checkboxbase#"
            },
            {
              "properties": {
                "separateSpecialChoices": {
                  "type": "string"
                }
              }
            }
          ]
        },
      "checkbox": {
          "allOf": [
            {
              "$ref": "checkboxbase#"
            },
            {
              "properties": {
                "separateSpecialChoices": {
                  "type": "string"
                }
              }
            }
          ]
        }
    }
}
```

**Comment by andrewtelnov** [comment]
@BinoDino I beleived I have fixed issues. You can check [this PR](https://github.com/surveyjs/survey-library/pull/6229).
Hopefully it will be merged before we relase next version tomorrow/after tomorrow.

Thank you,
Andrew

**Comment by BinoDino** [comment]
@andrewtelnov Sorry, I have something else - it's rather a question (or maybe a bug?):

I noticed that in the JSON schema there is no property `type` for the elements/questions. But when I use the Survey Creator a `type` property is even required (to identify the question type for rendering I suppose). 

Moreover, I noticed that there are no required Schema fields at all. But isn't it for example like this: 
* a `page` requires a `name` as unique identifier
* a `question`  requires a `name` as unique identifier and a `type` to define what kind of question it is

**Comment by andrewtelnov** [comment]
@BinoDino I have added "type" property into  "#question" and "#panel". It supports "required" array attribute as well.

Thank you,
Andrew

**Comment by BinoDino** [comment]
@andrewtelnov Thank you very much for the latest version of the surveyjs schema. I really appreciate your fast reply and fixes. I tested it today. Unfortunately I found two issues that were not fixed yet. 

## The issues are the following

### 1.  Error message: `invalid schema: data/properties/questions/items must be object,boolean`

#### current schema 

`items` attribute is an `array`

```json
{
  "properties": {
     "questions": {
         "type": "array",
         "items": [...]
      }
   }
}
```
#### expected schema 

`items` attribute is an `object` with `anyOf`, which is an `array`

```json
{
  "properties": {
     "questions": {
         "type": "array",
         "items": {
            "anyOf": [...]
      }
   }
}

```

Affected: 
* `properties/questions/items`
* `properties/triggers/items`
* `definitions/panelbase/properties/elements/items`
* `definitions/question/properties/validators/items`
* `definitions/matrixdropdowncolumn/properties/validators/items`
* `definitions/multipletextitem/properties/validators/items`
* `definitions/paneldynamic/allOf/{1}/properties/templateElements/items`

### 2.  Error message: `invalid schema: data/definitions/expressionitem/$id must match pattern "^[^#]*#?$"`

#### current schema 

Every attribute `$id` starts with `"#"`.

```json
{
   "htmlconditionitem": {
        "$id": "#htmlconditionitem"
   }
}
```
#### expected schema 

Remove `"#"` from `$id`, else it's invalid. 

```json
{
   "htmlconditionitem": {
        "$id": "htmlconditionitem"
   }
}
```

**Comment by andrewtelnov** [comment]
@BinoDino Regarding the second issue. Do you mean that all "$id" for all defintions should not have "#" symbol? 

Thank you,
Andrew

**Comment by BinoDino** [comment]
@andrewtelnov To your question: yes, that is correct.

**Comment by andrewtelnov** [comment]
@BinoDino Please review my commits in [this PR](https://github.com/surveyjs/survey-library/pull/6254).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@BinoDino Super, we are going to release v1.9.90 today.

Thank you,
Andrw
